# Création de variable(s)
@id=26f6c956-dc58-4df9-a5f6-586f8ed98be8
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4M2QwM2UyLWIyNWYtNDg0Mi05ZWRkLTM2NGQ4Y2NlYzQyYiIsIm5hbWUiOiJMYSBCb3VjaGVyaWUiLCJvd25lck5hbWUiOiJKZWFuLVBpZXJyZSIsImVtYWlsIjoiamVhbi1waWVycmVAZ21haWwuY29tIiwiZm9vZFR5cGVzIjpbIlBpenphIiwiQnVyZ2VyIiwiRnJlbmNoIl0sImlhdCI6MTc2NTk2ODAyMywiZXhwIjoxNzY2MDU0NDIzfQ.MmiQ7704KVYGE41m87c1j3-jDpV476zSbzbbjCsslhA

#-------------------------------------------------------------------------------

################################################################################
# Premiers test de routes, requêtes, avant de faire router/controller dans le
# 'app.ts'
################################################################################

### TEST GET
GET http://localhost:8000?id=1234&name=Toto

### TEST POST
POST http://localhost:8000
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe"
}

### TEST PUT
PUT http://localhost:8000/1234


### TEST POST JUSTE POUR INFO ###
POST http://localhost:8000
# Lorsque j'envoie un formulaire
Content-Type: multipart/form-data

################################################################################
# Fin des tests
################################################################################

#-------------------------------------------------------------------------------

################################################################################
# GET ROUTES
################################################################################

### GET Restaurants list ###
GET http://localhost:8000/v1/admin/restaurant

### GET Restaurant by id ###
GET http://localhost:8000/v1/admin/restaurant/{{id}}

### GET Restaurant profile ###
GET http://localhost:8000/v1/restaurant/profile
Authorization: Bearer {{token}}

################################################################################
# GET ROUTES
################################################################################

#-------------------------------------------------------------------------------

################################################################################
# POST ROUTES
################################################################################

### Admin CREATE restaurant ###
POST http://localhost:8000/v1/admin/restaurant/create
Content-Type: application/json

{
  "name": "La Boucherie",
  "ownerName": "Jean-Pierre",
  "foodTypes": ["Pizza", "Burger", "French"],
  "postalcode": "75001",
  "address": "Rue de la Paix",
  "phone": "0612345678",
  "email": "jean-pierre@gmail.com",
  "password": "123456"
}

### Login ###
POST http://localhost:8000/v1/restaurant/login
Content-Type: application/json

{
  "email": "jean-pierre@gmail.com",
  "password": "123456"
}

################################################################################
# POST ROUTES
################################################################################

#-------------------------------------------------------------------------------

################################################################################
# PATCH ROUTES
################################################################################

### Restaurant (user) UPDATE restaurant ###
PATCH http://localhost:8000/v1/restaurant/update
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Boucherie",
  "ownerName": "Jean-Pierre",
  "foodTypes": ["Pizza", "Burger", "French"],
  "address": "Rue de la Paix",
  "phone": "0612345678"
}

### UPDATE restaurant service available ###
PATCH http://localhost:8000/v1/restaurant/available
Authorization: Bearer {{token}}

################################################################################
# PATCH ROUTES
################################################################################

#-------------------------------------------------------------------------------

################################################################################
# PUT ROUTES
################################################################################



################################################################################
# PUT ROUTES
################################################################################
