# ------------------------------------------------------------------------------
# Premiers test de routes, requêtes, avant de faire router/controller dans le
# 'app.ts'
# ------------------------------------------------------------------------------

### TEST GET
GET http://localhost:8000?id=1234&name=Toto

### TEST POST
POST http://localhost:8000
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe"
}

### TEST PUT
PUT http://localhost:8000/1234


### TEST POST JUSTE POUR INFO ###
POST http://localhost:8000
# Lorsque j'envoie un formulaire
# Content-Type: multipart/form-data

# ------------------------------------------------------------------------------
# Fin des tests
# ------------------------------------------------------------------------------

### Admin CREATE restaurant
POST http://localhost:8000/admin/restaurant/create
Content-Type: application/json

{

}
